// The public API, written down. Lists every export of every entry point (values and types, with
// their shapes) into api/surface.txt, so a change to what users can import shows up in review.
//
//   node scripts/api-surface.mjs           check: fail if the API differs from api/surface.txt
//   node scripts/api-surface.mjs --update  rewrite api/surface.txt after an intended change
//
// Additions are fine in any minor release. A removal or a changed shape is a breaking change: it
// needs a deprecation first and a major release (docs/versioning.md).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
// TypeScript 7 has no stable JavaScript API yet, so this reads the code with TypeScript 6's.
import ts from "@typescript/typescript6";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRIES = {
  "hintbeam (web)": "src/web/index.ts",
  "hintbeam (react-native)": "src/native/index.ts",
  "hintbeam/core": "src/core/index.ts",
  "hintbeam/next": "src/routers/next.ts",
  "hintbeam/react-router": "src/routers/react-router.ts",
  "hintbeam/expo-router": "src/routers/expo-router.ts",
  "hintbeam/react-navigation": "src/routers/react-navigation.ts",
};
const OUT = resolve(root, "api/surface.txt");

// The naming rule for what apps import (docs/api.md, "Naming"): apps import Hintbeam next to a UI
// kit, a router and their own code, so nothing there may have a generic name. Every export is a
// hook (`use…`) or says "tour" — except these, which are already specific to Hintbeam.
const APP_ENTRIES = ["hintbeam (web)", "hintbeam (react-native)"];
const isSpecific = (name) => /^use[A-Z]/.test(name) || /Tour|TOUR_/.test(name);
const ALLOWED = new Set([
  "defineTargets",
  "DefineTargetsOptions",
  "TargetDefinition",
  "TargetName",
  "Register",
  "RegisteredTargetName",
  "AdvanceOn",
  "createManualRouter",
  "GuideOrb",
  "GuideOrbProps",
  "GuideMood",
  "UseTargetOptions",
  "webPlatform",
  "nativePlatform",
]);

const config = ts.getParsedCommandLineOfConfigFile(
  resolve(root, "tsconfig.json"),
  {},
  { ...ts.sys, onUnRecoverableConfigFileDiagnostic: () => {} },
);
const files = Object.values(ENTRIES).map((f) => resolve(root, f));
const program = ts.createProgram(files, { ...config.options, noEmit: true });
const checker = program.getTypeChecker();
const flags = ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope;

function describe(symbol) {
  const target = symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
  const decl = target.declarations?.[0];
  if (!decl) return "unknown";
  if (ts.isInterfaceDeclaration(decl) || ts.isClassDeclaration(decl)) {
    const kind = ts.isInterfaceDeclaration(decl) ? "interface" : "class";
    const type = checker.getDeclaredTypeOfSymbol(target);
    const members = checker
      .getPropertiesOfType(type)
      .filter((p) => !(p.valueDeclaration && ts.getCombinedModifierFlags(p.valueDeclaration) & ts.ModifierFlags.Private))
      .map((p) => {
        const optional = p.flags & ts.SymbolFlags.Optional ? "?" : "";
        const t = checker.typeToString(checker.getTypeOfSymbolAtLocation(p, decl), decl, flags);
        return `    ${p.name}${optional}: ${t}`;
      })
      .sort();
    return `${kind}\n${members.join("\n")}`;
  }
  if (ts.isTypeAliasDeclaration(decl)) {
    const params = decl.typeParameters ? `<${decl.typeParameters.map((p) => p.getText()).join(", ")}>` : "";
    return `type${params} = ${decl.type.getText().replace(/\s+/g, " ")}`;
  }
  if (ts.isEnumDeclaration(decl)) return "enum";
  const type = checker.getTypeOfSymbolAtLocation(target, decl);
  return `${ts.isFunctionDeclaration(decl) ? "function" : "const"}: ${checker.typeToString(type, decl, flags)}`;
}

const lines = [
  "# The public API of hintbeam. Generated by scripts/api-surface.mjs — do not edit by hand.",
  "# A removed or changed line is a breaking change (docs/versioning.md). Added lines are fine in a minor.",
  "",
];
for (const [name, file] of Object.entries(ENTRIES)) {
  const source = program.getSourceFile(resolve(root, file));
  const symbol = checker.getSymbolAtLocation(source);
  const exports = checker.getExportsOfModule(symbol).sort((a, b) => a.name.localeCompare(b.name));
  lines.push(`## ${name}`, "");
  // Formatting is not API: collapse whitespace and trailing commas that destructured parameters carry.
  const normal = (text) => text.replace(/\s+/g, " ").replace(/,\s*([}\]])/g, " $1");
  for (const e of exports) lines.push(`${e.name}: ${normal(describe(e))}`);
  if (APP_ENTRIES.includes(name)) {
    const generic = exports.map((e) => e.name).filter((n) => !isSpecific(n) && !ALLOWED.has(n));
    if (generic.length) {
      console.error(
        `${name} exports names that could clash with other libraries: ${generic.join(", ")}.\n` +
          "Name it after tours (TourThing, createTourThing, TOUR_THING), keep it in hintbeam/core, or allow it in scripts/api-surface.mjs.",
      );
      process.exit(1);
    }
  }
  lines.push("");
}
const next = lines.join("\n");

if (process.argv.includes("--update")) {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, next);
  console.log(`api/surface.txt updated (${next.split("\n").length} lines).`);
} else {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {}
  if (current === next) {
    console.log("Public API unchanged.");
  } else {
    const a = new Set(current.split("\n"));
    const b = new Set(next.split("\n"));
    const removed = [...a].filter((l) => !b.has(l) && l.trim());
    const added = [...b].filter((l) => !a.has(l) && l.trim());
    console.error("The public API changed.\n");
    for (const l of removed) console.error(`- ${l}`);
    for (const l of added) console.error(`+ ${l}`);
    console.error(
      `\n${removed.length ? "Lines were removed or changed: that is a BREAKING change (see docs/versioning.md)." : "Only additions."}` +
        "\nIf this is intended, run `npm run api:update`, commit api/surface.txt, and add a changeset (`npx changeset`).",
    );
    process.exit(1);
  }
}
